### PR TITLE
Adding support for almond complied products

### PR DESCRIPTION
**Pull request by claughlin-r7**
Adding support to allow use when the parent application is being build with [almond](https://github.com/jrburke/almond#incorrect-module-build-no-module-name), still maintains compatibility with other builders and module types.

### CODE REVIEW

**Comment by ccatalan-r7** [comment]
@farias-r7 mind taking a peek at reviewing this? a hack was required to get deps loaded properly for part of nx dashboard, may want to chat with @claughlin-r7 on this since he briefly mentioned this to me

**Comment by claughlin-r7** [comment]
Updated PR with latest master and all tests are passing. @abologna-r7 can provide info in this also as he came up with the fix.

**Comment by farias-r7** [comment]
@abologna-r7 is out until next week on vacation. I'll take a look. As long as specs are passing and we can use the compiled asset in Pro I think we should be fine.

**Comment by claughlin-r7** [comment]
@farias-r7 any update on this?

**Pull request merged**
